In [13]:
import numpy as np

In [14]:
from scipy.spatial.transform import Rotation

euler = np.array([0,  0, np.deg2rad(45)])
rot = Rotation.from_euler('XYZ', euler)
rot.as_matrix()

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [15]:
rot0 = Rotation.from_euler('XYZ', np.array([np.deg2rad(10), np.deg2rad(0), np.deg2rad(0)]))
rot1 = Rotation.from_euler('XYZ', np.array([np.deg2rad(0), np.deg2rad(20), np.deg2rad(0)]))
rot2 = Rotation.from_euler('XYZ', np.array([np.deg2rad(0), np.deg2rad(0), np.deg2rad(30)]))
print(rot0.as_quat())
print(rot1.as_quat())
print(rot2.as_quat())

[0.08715574 0.         0.         0.9961947 ]
[0.         0.17364818 0.         0.98480775]
[0.         0.         0.25881905 0.96592583]


In [16]:
class Quaternion():
    def __init__(self, w, x, y, z):
#       self.quat = np.array(w, x, y, z)
        self.w = w
        self.x = x
        self.y = y
        self.z = z
    
    @classmethod
    def from_rotation(cls, vec, theta):
        t = theta / 2
        s = np.sin(t)
        c = np.cos(t)
        return cls(c, vec[0]*s, vec[1]*s, vec[2]*s)    
    
    def as_tuple(self):
        return self.w, self.x, self.y, self.z
    
    def conjugate(self):
        return Quaternion(self.w, -self.x, -self.y, -self.z)    

    def norm(self, ord=2):
        return np.linalg.norm(self.as_vector(), ord=ord)

    def inverse(self):
        pass
    
    def __mul__(self, other):
        w0, x0, y0, z0 = self.as_tuple()
        if type(other) == Quaternion: 
            w1, x1, y1, z1 = other.as_tuple()
            return Quaternion(
                    w0*w1 - x0*x1 - y0*y1 - z0*z1,
                    x0*w1 + w0*x1 - z0*y1 + y0*z1,
                    y0*w1 + z0*x1 + w0*y1 - x0*z1,
                    z0*w1 - y0*x1 + x0*y1 + w0*z1,
                )
        else:
            Quaternion(0, 0, 0, 0)
        
    def as_vector(self):
        return np.array(self.as_tuple()).reshape(4, 1)
        
    def as_matrix(self):
        w, x, y, z = self.as_tuple()
        return np.array([
                    [w*w + x*x - y*y - z*z, 2*(x*y - w*z), 2*(w*y + x*z)], 
                    [2*(w*z + x*y), w*w - x*x + y*y - z*z, 2*(-w*x + y*z)], 
                    [2*(x*z - w*y), 2*(y*z + w*x), w*w - x*x - y*y + z*z], 
                ])
    
    def get_matrix2(self):
        w, x, y, z = self.get_tuple()
        return np.array([
                    [1 - 2*y*y - 2*z*z, 2*x*y + 2*w*z, 2*x*z - 2*w*y], 
                    [2*x*y - 2*w*z, 1-2*x*x - 2*z*z, 2*y*z + 2*w*x], 
                    [2*x*z + 2*w*y, 2*y*z - 2*w*x, 1 - 2*x*x - 2*y*y], 
                ])

In [17]:
q0 = Quaternion.from_rotation([1, 0, 0], np.deg2rad(10))
q1 = Quaternion.from_rotation([0, 1, 0], np.deg2rad(20))
q2 = Quaternion.from_rotation([0, 0, 1], np.deg2rad(30))

In [18]:
print(q0.as_tuple())
print(q1.as_tuple())
print(q2.as_tuple())

AttributeError: 'Quaternion' object has no attribute 'w'

In [ ]:
print((q0*q1*q2).as_tuple())

(0.943714364147489, 0.12767944069578063, 0.14487812541736914, 0.2685358227515692)


In [ ]:
rot = Rotation.from_euler('XYZ', np.array([np.deg2rad(10), np.deg2rad(20), np.deg2rad(30)]))
print(rot.as_quat())

[0.12767944 0.14487813 0.26853582 0.94371436]


In [ ]:
print(rot.as_matrix())

[[ 0.81379768 -0.46984631  0.34202014]
 [ 0.54383814  0.82317294 -0.16317591]
 [-0.20487413  0.31879578  0.92541658]]


In [ ]:
m = (q0*q1*q2).as_matrix()
print(m)

[[ 0.81379768 -0.46984631  0.34202014]
 [ 0.54383814  0.82317294 -0.16317591]
 [-0.20487413  0.31879578  0.92541658]]


In [ ]:
v = np.array([[1], [0], [0]])

In [ ]:
m @ v

array([[ 0.81379768],
       [ 0.54383814],
       [-0.20487413]])

In [ ]:
rot.as_rotvec()

array([0.26026043, 0.29531805, 0.5473806 ])